app = "kunafah-store-manegment"
primary_region = "iad"

[build]
dockerfile = "Dockerfile"

[env]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"

[[mounts]]
source = "whatsapp_data"
destination = "/app/whatsapp_data"
